### ISSUE TITLE
Unable to create splash screen using Fluid

### ISSUE THREAD

**Issue by edips** [benlau/androidnative.pri#12]
I tried it for app and I got the error: 
`qrc:/main.qml:14 ((null)): qrc:/main.qml:14:25: Unable to assign int to QQuickAnchorLine`
It linked to `initialPage: Components` , it didn't recognize this.
I also couldn't run the example app, it gave error: 
../androidnativeexample/main.cpp:7:32: fatal error: qadrawableprovider.h: No such file or directory
` #include "qadrawableprovider.h"`
I read your blog about splash screen for Android and came here directly, Thanks

**Comment by rmallah** [comment]
Hi edips , this will go away just install 

https://www.qpm.io/packages/com.github.benlau.quickandroid/index.html

**Comment by edips** [comment]
Hi rmallah I managed to show splash screen before without using animation scripts. I forgot to close the subject. It would be great to run animated codes, I will try your suggestion . Thank you.
