### ISSUE TITLE
QPM package Version

### ISSUE THREAD

**Issue by Skycoder42** [benlau/androidnative.pri#2]
I am a little confused regarding the "up to date"-ness of the qpm package? In qpm, it's version 0.0.4, in your github qpm file, it states 0.0.5, and on your release page you are already at version 0.1.7

Is the qpm package simply not up to date? Or how do I have to understand those versions?

**Comment by benlau** [comment]
Thank for pointing out the problem. The latest version is 0.0.5, but probably I did a mistake in release, and therefore the version is not available in qpm.io . I just published it again.

The v0.1.7 is the old tags from QuickAndroid project. I have just removed them.
